[package]
name = "web_traffic_tracker"
version = "0.1.0"
authors = ["jBosak <jbosak98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pcap = "0.7.0"
argparse = "0.2.2"
amiquip = "0.2.2"